### ISSUE TITLE
enrich pit CSV with information 

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#122]
* assertion failure or exception error
* test line of failure/error

PR on PIT?

**Comment by oscarlvp** [comment]
The XML report that comes with PIT provides a bit more of information regarding the mutation, but it doesn't include this kind of runtime information.
A new reporter can be included as a plugin but it will receive the information regarding mutation and coverage already computed. So, in order to do this we have to dig deeper.
Information about a possible thrown exception after running a test (coming from an assertion failure or not)  is stored in the [TestResult class](https://github.com/hcoles/pitest/blob/ea201199e6af828727760a2bde041819958b6ea0/pitest/src/main/java/org/pitest/testapi/TestResult.java#L40) which is inspected by the [Pitest class](https://github.com/hcoles/pitest/blob/8c9edd5881ccb5ffd3548f62c57d0133270f3cd1/pitest/src/main/java/org/pitest/testapi/execute/Pitest.java#L81) and passed to a TestListener. A custom listener can be injected when the instance of Pitest is created probably [here](https://github.com/hcoles/pitest/blob/8c9edd5881ccb5ffd3548f62c57d0133270f3cd1/pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestWorker.java#L196)  or modify the one in use and the [MutationStatusTestPair](https://github.com/hcoles/pitest/blob/8c9edd5881ccb5ffd3548f62c57d0133270f3cd1/pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestWorker.java#L209) class should be also modified to hold the instance of the Throwable so the reporter can access it directly.
With the Throwable at hand we can check the type of the exception thrown and see if it was an assertion failure and we can inspect the stack trace which should contain information about the line of code that failed.

**Comment by monperrus** [comment]
Super interesting, thanks. Do you think that a new reporter would be enough to get at least the
error/failure information?

**Comment by danglotb** [comment]
Another information that could be useful for me is to have the list of all failing test instead of only one.  

I see [here](https://github.com/hcoles/pitest/blob/8c9edd5881ccb5ffd3548f62c57d0133270f3cd1/pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestWorker.java#L210), pit takes the last failing test.

I will look to open a PR ASAP.

**Comment by oscarlvp** [comment]
@monperrus No, we'll need to change both the code base and also the reporter, but it seems feasible.
@danglotb I did that already. The matrix branch of our pitest fork is a modified pitest that will run all tests related to a mutation instead of exiting with the first test that fails. The behaviour is controlled by a parameter named buildMatrix. Only the command line entry point of pitest has support for this parameter right now, but I think is not hard to include support for maven. I realised now that I haven't pushed the matrix branch into the github repo :)

**Comment by monperrus** [comment]
> The matrix branch of our pitest fork
Could this be a PR on Pit's master?

**Comment by oscarlvp** [comment]
Probably we'll first need to add support for pitest-maven and change all default reporters to include the information of all failed tests. That could take some time. Right now the only reporter supporting this is a custom JSON reporter with I added to descartes.

**Comment by monperrus** [comment]
> Right now the only reporter supporting this is a custom JSON reporter with I added to descartes

How to use this custom JSON reporter?

**Comment by monperrus** [comment]
@oscarlvp 

How to use the custom JSON reporter?

**Comment by oscarlvp** [comment]
Just add `descartes` as a dependency for the plugin and later specify JSON as the report file format. like this:
```xml
<outputFormats><value>JSON</value></outputFormats>
```

**Comment by monperrus** [comment]
Thanks.
