### ISSUE TITLE
DSpot: No new amplified test are generated by executing DSpot on Atos UC Supersede component.

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#162]
**Issue Type**: possible misuse or wrong target software module for testing amplification
**Description**: DSpot executed on customed Atos UC Supersede IF component, on a concrete test suite returns 0 amplified tests:

======= REPORT =======
PitMutantScoreSelector: 
The original test suite kill 0 mutants
The amplification results with 0 new tests
it kill 0 more mutants

Questions?
1- What are suitable test cases to validate DSpot? What characteristics should they and the software being tested show?

**Reproducibility**: always
**Severity**: minor
**Tool**: DSpot GitHub repository, version 28/08/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
See https://github.com/STAMP-project/dspot/issues/161 for setting up the testing environment.
Then, from Dspot folder, in CMD, execute: 
`java -cp target/dspot-1.0.0-jar-with-dependencies.jar fr.inria.stamp.Main -p ./src/test/resources/test-projects/test-projects-supersede-if.properties -t eu.supersede.integration.api.security.test.IFAuthenticationManagerTest`
**Files**:
I attach the full log of executing DSpot on Atos Supersede IF component:
[DSpot_execution_supersede_if_single_test.txt](https://github.com/STAMP-project/dspot/files/1256964/DSpot_execution_supersede_if_single_test.txt)

**Relationships**: See https://github.com/STAMP-project/dspot/issues/161
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
I think it is the same problem explained in #161 

We see in the report of DSpot that even the original test suite does not kill any mutant:
>======= REPORT =======
PitMutantScoreSelector:
The original test suite kill 0 mutants
The amplification results with 0 new tests
it kill 0 more mutants

It is probably due to the filter.

However:
> What are suitable test cases to validate DSpot? What characteristics should they and the software being tested show?

Your question is really interesting.

I would say that we should avoid parametrized and mocked test cases first, because the amplification of the input of the test would be stuck: DSpot does not amplify parameter or construction of mock (also an interesting feature btw).

In the other hand, a great target source class for DSpot is a class with `getters` such as conventional getters in java: no parameters, a return type and starts with **get**, **is** or **should**.

**Comment by jesus-gorronogoitia** [comment]
in #161 I reported a classpath issue, but as you think it may be cause by the filter configuration issue, lets close this waiting to fixing #161 by correcting the filter.
