### ISSUE TITLE
Documentation: Improve

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#179]
* Fix errors in the final reporst of PitMutantScoreSelector
* Update README with new options and values for options.

**Comment by nicolabertazzo** [comment]
Hi @danglotb 

This command line properties is not documented:

- path-to-test-list-csv

This dspot.proerties properties is not documented:

- configPath

The name of this dspot.properties is not clear:

- folderPath

I suggest to add a description of this properties also in dspot-diff-test-selection (because it's mandatory when you want to use dispot-diff)
