### ISSUE TITLE
o mutations found. This probably means there is an issue with either the supplied classpath or filters

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#231]
**Issue Type**: possible bug/misuse
**Description**: Following the Nicola's [DSpot for dummies tutorial](https://github.com/nicolabertazzo/dspot/blob/dspot-for-dummies/docs/dspot-for-dummies.md), the application of DSpot to dhell project reports:
No mutations found. This probably means there is an issue with either the supplied classpath or filters.
This issue was reported for Descartes (see issue 26) when following similar tutorial for Descartes, error that was caused by a wrong DHell project pom.xml file. When following this tutorial and running DSpot, I use a checked out version of Dhell pom.xml.
**Reproducibility**: always
**Severity**: major
**Tool**: DSpot, version 16/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**: Follow the steps in the _DSpot for dummies tutorial_.
**Files**: See Maven execution logs attached.
[dspot_dhell_dummies_test_v1.txt](https://github.com/STAMP-project/dspot/files/1388112/dspot_dhell_dummies_test_v1.txt)

Relationships: Descartes issue 26
Reporter: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I can see in your stacktrace that you have the following line, which are maven's goal to run pit:
` run maven  org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=myWorld* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/`

The most important here, is the value of the targetClasses:  `-DtargetClasses=myWorld*`

In fact this is wrong, it should be `-DtargetClasses=fr.inria.stamp.examples.dhell*`

Could you please checks that your properties files contains the right filter:
```
filter=fr.inria.stamp.examples.dhell*
```

I can see that you point to the @nicolabertazzo's fork of DSpot. In fact, the doc for dummies on this fork is not updated. You should have a look to the doc on the [main repository of DSpot](https://github.com/STAMP-project/dspot/blob/master/docs/dspot-for-dummies.md), because @CaelInria made the update/fix on the filter property.

I'm gonna take the opportunity to tell you that with recent changes, DSpot is not able to run Descartes. DSpot can only run mutation analysis done by the gregor mutation engine, _i.e._ the default mutation engine of pit.

Thank you very much for trying DSpot and Descartes, and sorry for the delay.

Cheers,

-- Benjamin.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin,
Merci, your DSpot tutorial works well, so I could run DSpot on DHell project. Now, I will try to run it on my own projects. I will report to you my results.
I close this issue, as it is resolved.
Yosu
