### ISSUE TITLE
Deployment on Maven Central

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#289]
It would be great to deploy **DSpot**, and others tools to Maven central.

But, we have to remove the following tag from the `pom.xml`:

```
<repositories> ... </repositories
```

That means that we have to replace the dependency: 
```
<dependency>
    <groupId>org.gradle</groupId>
    <artifactId>gradle-tooling-api</artifactId>
    <version>4.0.1</version>
</dependency>
```

and deploy also **Descartes** on maven central.

**Comment by danzone** [comment]
Hi @danglotb , removing gradle tooling API dependency would hurt the Gradle projects support on DSpot. I need to evaluate the impact. Why is it necessary to remove the dep?

**Comment by danglotb** [comment]
According to [this](https://maven.apache.org/guides/mini/guide-central-repository-upload.html), the tag `<repositories>` is not allowed.

**Comment by monperrus** [comment]
@danzone to make progress on this, could you deploy our own version of gradle-tooling-api to Maven Central, under groupiD `org.stamp-project` for example?

**Comment by danzone** [comment]
Hi @monperrus , we don't have our own version of gradle-tooling API: it's an official dependency, that's why we reference it throw official Gradle repositories. I've checked the Maven guide: `<repositories>` tag is strongly discouraged, but it would not preclude STAMP artifacts from being included. According to FAQ available in [this page](https://maven.apache.org/guides/mini/guide-central-repository-upload.html):

> At present, this won't preclude your project from being included, but we do strongly encourage making sure all your dependencies are included in Central. If you rely on sketchy repositories that have junk in them or disappear, it just creates havok for downstream users. Try to keep your dependencies among reliable repos like Central, Jboss, etc.

I guess the official Gradle tooling API repository `https://repo.gradle.org/gradle/libs-releases-local/` should be considered reliable. At the same time I guess we couldn't include official Gradle tooling API in Maven central (without their permissions... )

**Comment by monperrus** [comment]
> I guess the official Gradle tooling API repository
> |https://repo.gradle.org/gradle/libs-releases-local/| should be considered reliable
I agree. It will likely be accepted by Central.

Is gradle-tooling there?

**Comment by danzone** [comment]
Yes, you can find it at https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/

**Comment by monperrus** [comment]
Excellent. So it means we can add this repository to the pom.xml and deploy a first version to Maven
Central.

@danglotb: OK for you?

**Comment by danglotb** [comment]
I'm OK,

We need to deploy **Descartes** en Maven central. 

I may be the opportunity to fix the usage of **Descartes** inside **DSpot**.

**Comment by danglotb** [comment]
**DSpot** has been released yesterday: see [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cdspot)

**Comment by monperrus** [comment]
Excellent! Thanks to all for the effort put in this!
