### ISSUE TITLE
Forked DSpot build fails on Travis

### ISSUE THREAD

**Issue by danzone** [STAMP-project/dspot#298]
I just rebased my DSpot fork (https://github.com/danzone/dspot), but the Travis automatic build fails with the following error message:

`The command "mvn clean install" exited with 1.
0.01s$ cd dspot && java -jar target/dspot-1.0.5-SNAPSHOT-jar-with-dependencies.jar --example
Error: Unable to access jarfile target/dspot-1.0.5-SNAPSHOT-jar-with-dependencies.jar`

I attached the whole log.

Any idea about what's wrong with my build?
[log.txt](https://github.com/STAMP-project/dspot/files/1625796/log.txt)

**Comment by danglotb** [comment]
Hi @danzone 

The build fails because of the version of PIT. The new version of PIT create more mutants, and so one assertions fails. Maybe we have an over specification here.

I create a fix in #294 (sorry for mix fix and features), in order to make my PR green.

It should be merge in the future days.

-- Benjamin.

**Comment by monperrus** [comment]
closed per #294

**Comment by danzone** [comment]
Hi @monperrus @danglotb, I rebased my fork, now everything is fine also in Travis. Thank you!
