### ISSUE TITLE
Running DSpot within Eclipse in Windows

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#324]
**Issue Type**: possible bug/misuse
**Description**: We are developing a Eclipse plugin that assists developers to execute DSpot on a selected project within the IDE, using the DSpot CLI. Execution works well on Linux, but not on Windows where DSpot get blocked in the middle of execution. To narrow down this experimentation, we tried to launch DSpot from another Java program that uses Runtime.exec() method, invoking an script (sh or bat) that executes DSpot using its CLI. The execution of this script works well from the CLI in both Linux and Windows OS, but not not from the Java Runtime.exec() program for Windows (it works for Linux). Tested with dhell project.
**Reproducibility**: always (always, sometimes, random)
**Severity**: major (feature, minor, major, crash, block)
**Tool**: Descartes PITest, version 14/02/18
**Execution Environment**: Windows7, Windows10
**Steps to reproduce**:
Download attached batch file dspot.bat into your dhell folder. Similarly download the attached dpot.properties into the same folder. Use the following class main method to invoke this script, from Eclipse or another IDE. Before executing configure the dhell path.

```
public static void main(String[] args) {
	
	String command = "cmd /C E:\\Atos\\STAMP\\Git\\dhell\\dspot.bat";
	
	try {
		Process pro = Runtime.getRuntime().exec(command);
		
		InputStream input = pro.getInputStream();
		BufferedReader bfr = new BufferedReader(new InputStreamReader(input));
		
		InputStream error = pro.getErrorStream();
		BufferedReader errorBfr = new BufferedReader(new InputStreamReader(error));
		//pro.waitFor();
		
		String line = null, errorLine = null;
		while((line = bfr.readLine()) != null || (errorLine = errorBfr.readLine())!= null) {
			System.out.println(line);
		}
		
	} catch (IOException e) {
		e.printStackTrace();
	} 
	
}  // end of the main
```

See attached the DSpot logs when executing the script from the CLI:
[dspot_successful_execution.txt](https://github.com/STAMP-project/dspot/files/1725056/dspot_successful_execution.txt)

See attached the DSpot logs when executing the script from Java program: 
[dspot_unsuccessful_execution_with_verbose.txt](https://github.com/STAMP-project/dspot/files/1725057/dspot_unsuccessful_execution_with_verbose.txt)
[dspot_successful_execution.txt](https://github.com/STAMP-project/dspot/files/1725058/dspot_successful_execution.txt)

**Files**:
[dspot.bat.txt](https://github.com/STAMP-project/dspot/files/1725071/dspot.bat.txt)
[dspot.properties.txt](https://github.com/STAMP-project/dspot/files/1725072/dspot.properties.txt)

**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by jesus-gorronogoitia** [comment]
Questions?
1- Comparing these execution logs, do you see something weird that can provide you a hint for us to know where (within DSpot code) to investigate/debug?
2- I assume, DSpot CLI gets all user inputs and invoke an internal API.
What is the DSpot entry point, containing a main method that is invoked when CLI issues a:
`java -jar dspot-1.0.6-SNAPSHOT-jar-with-dependencies.jar`?
Inspecting that class we could understand how to invoke DSpot programmatically and not through the CLI
Thanks

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

> 1- Comparing these execution logs, do you see something weird that can provide you a hint for us to know where (within DSpot code) to investigate/debug?

**DSpot** is stuck when it tries to run instrumented test  according to the last logs:
> 2018-02-14 17:56:59,307 INFO fr.inria.diversify.dspot.assertGenerator.MethodsAssertGenerator - Run instrumented tests. (21)

This step is done in: [fr.inria.diversify.dspot.assertGenerator.MethodsAssertGenerator](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodsAssertGenerator.java#L140)

So, **DSpot** could be stuck because it is not able to compile the new tests: see [fr.inria.diversify.dspot.support.TestCompiler#compileAndRun](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/dspot/support/TestCompiler.java#L34) which call (fr.inria.diversify.dspot.support.DSpotCompiler#compile)[https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/dspot/support/DSpotCompiler.java#L85]
The problem can be about separator. In Windows, I think the path separator is `\` while on Linux is `/` right? But I thought that we could use both `/` and `\` on windows.

> What is the DSpot entry point, containing a main method that is invoked when CLI issues a:
`java -jar dspot-1.0.6-SNAPSHOT-jar-with-dependencies.jar`?

The entry point is [fr.inria.stamp.Main](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/stamp/Main.java). This class uses users' inputs to build a [fr.inria.stamp.Configuration](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/stamp/Configuration.java) then, setting up **DSpot** and others stuff.

In my opinion, we can skip the part of the `fr.inria.stamp.Configuration` and build directly a `DSpot` object. You must build an `InputConfiguration` and an `InputProgram`. Every configuration of `DSpot` is done using [constructors](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/dspot/DSpot.java).

The `Main` object can inspire you and you will be able to do whatever you want I think.

Finally, you will have to call one `amplify` method of the `DSpot` object, _e.g._ [fr.inria.diversify.dspot.DSpot#amplifyTest(String)](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/dspot/DSpot.java#L145) that will amplify test classes that match the given regex, _e.g._ `dspot.amplifyTest("fr.inria.*");` while amplify all **test classes** of the package `fr.inria` and sub packages.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Collegues,
merci beaupcoup, using the internal API Ricardo has been able to execute DSpot programmatically. He is now to integrate this approach in the Eclipse Wizard.
Thanks for your support.

**Comment by monperrus** [comment]
Excellent, closing this one.

> He is now to integrate this approach in the Eclipse Wizard

Thanks! Opened #332 for this one.

**Comment by monperrus** [comment]
@jesus-gorronogoitia what's Ricardo's github login?
