### ISSUE TITLE
Testing DSpot with Atos-Supersede-IF test suite with different selectors

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#329]
**Issue Type**: test report, possible bugs faced
**Description**: We have tested DSpot on Atos SUPERSEDE IF TestSuite, running experiments with different selectors. 
With JacocoCoverageSelector DSpot completed processing.
See experimental results at: [JacocoCoverageSelector test](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/2018-02-19_15:51:01)
With CloverCoverageSelector DSpot stopped at certain point, but keeps alive with quite low CPU usage, without showing any logs
See experimental results at: [CloverCoverageSelector test](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/2018-02-19_16:32:07)
With PitMutantScoreSelector DSpot broke showing an exception
See experimental results at: [PitMutantScoreSelector test](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/2018-02-19_16:45:03)
With default selector DSpot broke showing an exception
See experimental results at: [default selector test](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/2018-02-19_16:46:11)
**Reproducibility**: always (always, sometimes, random)
**Severity**: minor (feature, minor, major, crash, block)
**Tool**: Descartes PITest, version 19/02/18
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
Get Atos Supersede Integration framework (IF):
`git clone https://github.com/supersede-project/integration.git -b descartes`
Then, go to the IF project:
`cd integration/IF/API/eu.supersede.if.api/`
Edit executeDSpot_v3.sh. Modify paths for RESULTS_DIR and DSPOT_JAR. Uncomment the corresponding DSPOT_OPTS for DSpot execution
Execute executeDSpot_v3.sh
See logs at $RESULTS_DIR
**Files**:
**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

Sorry for the delay.

This very interesting, thank you very much!

>With JacocoCoverageSelector DSpot completed processing.
>See experimental results at: JacocoCoverageSelector test

**DSpot** has been able to amplified test that increase the coverage! That a good start.

According to the script, you made one iteration with only one amplifier (`MethodAdd`) enabled.

Would you mind to retry with: more iteration (increase the value of the parameter `-i`, _e.g._ 3) and add more amplifiers to create new test data input: `--amplifiers MethodAdd:StatementAdd:TestDataMutator` for instance? (It will take longer).

> With PitMutantScoreSelector DSpot broke showing an exception
> See experimental results at: PitMutantScoreSelector test

It is because the documentation is totally wrong.
The value of the property `filter` is used by PIT. The mutant that PIT generate will be inside this given filter. 

In your case, you gave `eu.supersede.integration.api.replan.controller.proxies.test*`. Here, this package does not contain any source code, but only test code. That is why PIT said:
> 4:45:41 PM PIT >> INFO : Created  0 mutation test units
Because it does not mutate the test code.

You have two options here: 
1. set the value to a large package, _i.e._ `eu.supersede.integration.*` which is your top level package. With this, PIT will analyze all the source code. In this case, you will have a "complete" analysis, but it will take more time (like a lot of time, the worst is the first analysis).
2. reduce the scope of the filter to a specific package (or even class). In this case, PIT will analyze only the matching source code. In the case you amplify `eu.supersede.integration.api.replan.controller.proxies.test.ReplanControllerProxyTest`, you would like analyze at least `eu.supersede.integration.api.replan.controller.proxies.ReplanControllerProxy` or the whole package `eu.supersede.integration.api.replan.controller.proxies.*` for instance.

If this is not clear, I give you more details about this selector.

> See experimental results at: CloverCoverageSelector test
> With PitMutantScoreSelector DSpot broke showing an exception

I'll investigate on my side why **DSpot** is stuck, thank you.

> With default selector DSpot broke showing an exception
> See experimental results at: default selector test

I strongly discourage you to use this selector (which is deprecated and will be remove ASAP).
This selector is old, and rely on a personal implementation of a JaCoCO-like algorithm.
You would rather use the JacocoCoverageSelector or CloverCoverageSelector, which are both using external and dedicated tools.

Thank you again, I'll come back to you ASAP.

**Comment by monperrus** [comment]
Hi Yosu,

That's really cool!

In order to easily browse https://github.com/STAMP-project/dspot-usecases-output/, I propose the following convention:

     https://github.com/STAMP-project/dspot-usecases-output/<partner>/<project>/<selector>/<amplifier>/<date>/**

So the file above case, we would have for example

     https://github.com/STAMP-project/dspot-usecases-output/atos/supersede/pit-mutant-score-selector/MethodAdd/<date>

WDYT?

**Comment by jesus-gorronogoitia** [comment]
Martin, 
Benjamin is proposing me to conduct experiments with multiple amplifiers, for example
--amplifiers MethodAdd:StatementAdd:TestDataMutator
In this case, how should the test repository be structured?, Something like:
 https://github.com/STAMP-project/dspot-usecases-output/<partner>/<project>/<selector>/<amplifier1:amplifier2>/<date>/**

Apart from this, what you proposed me is fine with me

**Comment by danglotb** [comment]
Yes, I think we can replace the `<ampifier>` by the list of used amplifiers, such as you proposed : `MethodAdd:StatementAdd`.

Keep in mind that, in **DSpot**, the order of amplifier does not matter, but maybe for the result, it would be better to keep a specific and arbitrary order. 

I think you can choose the order.

Thank you!

**Comment by jesus-gorronogoitia** [comment]
I am adapting my execution scripts to report DSpot results according to this reporting folder structure.

**Comment by monperrus** [comment]
Thanks.

Closing the issue for cleaning.
