### ISSUE TITLE
Change JSAP parsing to split multiple test cases (and other arguments as well) with OS-independent separator

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#352]
#### Characteristics

- **Issue Type**: possible bug/misuse

- **Reproducibility**: always

- **Severity**: major

- **Tool/Service/Component**: DSpot ( dspot-1.0.6-SNAPSHOT-jar-with-dependencies ) 

- **Execution Environment**: Windows 7 Enterprise

- **Reporters**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net
 & Ricardo José Tejada ricardo-jose.tejadagarcia@atos.net

#### Description
DSpot fails when using two or more test cases (an exception IndexOutOfBounds in fr.inria.stamp.Main is thrown)
Dspot works well when using only one test case (it works well with all the test cases used one by one) or without the -c parameter.
[ProblemTestCases.txt](https://github.com/STAMP-project/dspot/files/1788985/ProblemTestCases.txt)

#### Steps to reproduce
Execute DSpot over project dhell with several test cases
example :
(cmd order) java -jar C:\...\dspot-1.0.6-SNAPSHOT-jar-with-dependencies.jar -p C:\...\dhell\dspot.properties -i 1 -t fr.inria.stamp.examples.dhell.HelloAppTest -a MethodAdd -c testHelloAppIntString:testHelloAppRun1 (the same problem using other test cases).

the same problem using -t fr.inria.stamp.examples.dhell.MyStorageTest and -c testMyStorageString:testAddData (or other combination).
#### Other files and URLs
ProblemTestCases.txt

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @RicardoTej 

The problem come from the used separator _i.e._ `:`. This path separator is used on Linux and MacOS, but on Windows, you should use the specific separator, which is `;`.

Maybe the documentation is misleading you to use the wrong separator, which means that we need to fix it.

Also, I suggest you to update your projects, _e.g._, the `dhell` is no more using the groupId `fr.inria.stamp` but rather `eu.stamp`.

Thank you!

**Comment by jesus-gorronogoitia** [comment]
I strongly suggest to use the same separator regardless the OS of the DSpot users, otherwise, that would led to misuses and errors. I think DSpot can detect the OS under which it is being executed and replace the separator accordingly. If you want us to take care, let me know and I will modify the code in the  class that parses the DSpot configuration. Please, point me at that class.

**Comment by danglotb** [comment]
[JSAP](http://www.martiansoftware.com/jsap/) takes care of the parsing of the argument.

You can have a look to the [`fr.inria.stamp.JSAPOptions`](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/stamp/JSAPOptions.java) class.

**Comment by jesus-gorronogoitia** [comment]
Martin, this is the kind of engineering tasks we can take care at the moment, provided that we don't have a deep understanding of DSpot and Descartes internal process. In T1.4 we will take care of investigating ways to improve performance on both tools. During this period of proposal writing I am quite busy, but from May on, we will work on it.

**Comment by danglotb** [comment]
I thought about this.

In my opinion, this is a bad idea to use the same separator on all operating systems, since those separators appear in the command line.

In fact, which one we could use? Linux uses `:` however, we cannot use it on Windows since it is a special character, _e.g._ in a path `C:a/path/`.
In the same way, we cannot use `;` since it is a separator for commands on Linux.

The best solution is that the users must adapt their command line/arguments, according to the OS they use.

**Comment by danglotb** [comment]
I'm gonna close this issue because It has not been updated since a while. 

In addition to this, I have serious doubt about the implementation of this.

If you want to work on this, please feel free to reopen it.
