### ISSUE TITLE
Long DSpot execution time in Atos Supersede IF Test Suite

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#386]
#### Characteristics
- **Issue Type**: test report
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot, compiled version 28/03/18
- **Execution Environment**: Linux Tumbleweed
- **Reporter**: Jesús Gorronogoitia: jesus.gorronogoitia@atos.net

#### Description
DSpot was executed on one Atos IF Supersede test class (ReplanControllerProxyTest), This is a system test with intense I/O data exchange between a client and a remote service. Individual test suite execution with:
`mvn test -Dtest=ReplanControllerProxyTest`  
took 50 sec

> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 49.635 s
> [INFO] Finished at: 2018-04-02T11:37:43+02:00
> [INFO] Final Memory: 15M/303M
> [INFO] ------------------------------------------------------------------------

DSpot amplification with following configuration

`-i 3 -t eu.supersede.integration.api.replan.controller.proxies.test.ReplanControllerProxyTest -a MethodAdd:StatementAdd:TestDataMutator -s JacocoCoverageSelector`

took  12h:31m:24s

From these results, I identify these issues:
- IF test is a system test with high I/O demand, and low CPU consumption
- DSpot amplification takes long time to amplify these kind of system tests. Tracking CPU consumption shows quite low CPU usage. I assume this is due to intensive I/O communications with remote services
- Most of Atos Supersede test suites are system tests and show demanding I/O activity

#### Steps to reproduce
Clone Atos Supersede IF repository (descartes branch)
`git clone https://github.com/supersede-project/integration.git -b descartes`
Got to folder integration/IF/API/eu.supersede.if.api
Configure DSpot execution in ./executeDspot.sh
Launch ./executeDspot.sh script.

#### Other files and URLs
See results published in [DSpot UC results repository](https://github.com/STAMP-project/dspot-usecases-output):
[DSpot Execution Results](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/JacocoCoverageSelector/MethodAdd:StatementAdd:TestDataMutator/2018-03-28_08:48:05)
#### Relationships
N/A
#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

In fact, during the amplification process **DSpot** executes the tests a lot of time.

For one iteration of the main loop, it executes them (1 + 3 + 1) (Assertions Amplification) + 1 (in the case of the `JacocoSelector`) = 6 times each test methods.

In each iteration, **DSpot** limits the number of amplified test to 200, or less (by default, configurable with `--max-test-amplified <value>` command line option). That result, for one iteration with 1200 executions of variants of the same test method.

For `ReplanControllerProxyTest#testGetPlanOfReleaseByIdOfProjectById`, which takes a long time to be executed (8 seconds) it results with `1200 * 8 = 9600` s, approx. 2.5 hours. This calculation is not exact, since we won't have always 200 tests and some tests / executions won't take each time 8 seconds.

We can see that we can reach easily the 12 hours, and seems there is not a lot of things to do since this due to the execution time of the original test.

You can still reduce the number of test kept at each iteration with `--max-test-amplified <value>`, but you may miss some "interesting" amplified test methods.

We could also reduce the number of time that **DSpot** executes tests. For instance, during the Assertions Amplification, **DSpot** executes each test case 5 times. 

But this required to modify **DSpot**'s code.

1. One time to collect passing / failing test (without any assertions) to detect which test methods set the program under a bad state and create test method with a `try/catch/fail` statement. It seems that this execution cannot be remove. Here, we could configure that we don't want the second category, _i.e._ with a `try/catch/fail` statement, to reduce the number of test.

2. Three times to "verify" that amplified tests are not flaky: it compares output and discard any test that have different output between executions. (When I say outputs, I mean observable values of the program state, _i.e._, values obtained using `getters` on the program. There is no assertions yet.). Here, we could remove 2 executions. We may introduce flaky test in Amplified Tests (more than if we verify).

3. One time to verify that all amplified tests pass. We could remove this verification, but handle failing tests during the selection of tests.
