### ISSUE TITLE
Tests generated by DSport decreased the mutation score of the module

### ISSUE THREAD

**Issue by tmortagne** [STAMP-project/dspot#575]
Version: caba4a708b387f8dca2211f44242a7fa90026a08
Command: `java -jar ~/.m2/repository/eu/stamp-project/dspot/1.1.1-SNAPSHOT/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties`

The tests generated by DSpot for the module https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-core/xwiki-commons-crypto/xwiki-commons-crypto-common actually decreased the Mutation score from 70% to 69% (according to Descartes).

See https://github.com/tmortagne/dspot-usecases-output/tree/master/xwiki/2018-16-16-commons-crypto-common for more details.

**Comment by danglotb** [comment]
Okay, but **DSpot** does not use the configuration in your `pom.xml`.

**Comment by tmortagne** [comment]
> Okay, but DSpot does not use the configuration in your pom.xml.

I understand, just indicated where the mutation score I indicated is coming from.

**Comment by tmortagne** [comment]
> Could you provide both mutation reports, original and with the amplified test?

See descartes-before.zip and descarte-after.zip in https://github.com/STAMP-project/dspot-usecases-output/tree/master/xwiki/2018-10-16-commons-crypto-common.

**Comment by vmassol** [comment]
@danglotb ok I didn't realize/know that Dspot was using PIT without descartes. I was actually considering that it was the default since Dspot/Descartes are both in STAMP and that Descartes is what we use for STAMP. From now on we'll run Dspot on XWiki by specifying the `--descartes` flag. Thx

**Comment by danglotb** [comment]
@tmortagne The result in the zips indicate that the amplification increase the mutation score by 1% and increase the number of mutant covered by 2. There is an error? Did inverse both reports? 
Also, I suggest to use CSV reports, which give the state on mutants that created errors. You can compare these errors between runs, to ensure that you have at least the same number, and thus compare both results otherwise there is a bias.

@vmassol When I implemented the usage of PIT inside **DSpot** I needed the maximum number of mutants, and Descartes does not create a lot of mutants and was in developement. But today, I agree that we could use Descartes as the default mutation engine.

**Comment by vmassol** [comment]
@danglotb ok thanks for the explanation, I've created https://github.com/STAMP-project/dspot/issues/580

**Comment by tmortagne** [comment]
> @tmortagne The result in the zips indicate that the amplification increase the mutation score by 1% and increase the number of mutant covered by 2. There is an error? Did inverse both reports?

I rebuilt it today without checking the result and indeed it changed. I got 69% several times yesterday.

I just rebuilt it again and got 70% this time. Looks like the calculation is not very stable.

**Comment by tmortagne** [comment]
Anyway since it's not the same criteria you can probably close this issue as not very accurate.
