### ISSUE TITLE
Check inputs

### ISSUE THREAD

**Issue by CaelInria** [STAMP-project/dspot#605]
Inputs values are not checked, e.g. a wrong qualified name, and DSpot does not raise the corresponding error

**Comment by jesus-gorronogoitia** [comment]
Hi @CaelInria Thanks a lot for reporting this issue on behalf myself. 
In my experience, a significant number of issues reported by me where caused by wrong usage of DSpot CLI or wrong format or acceptable values for some parameters. However, the issues (raised as exceptions) that prevent DSpot to complete the work seemed to be unrelated to the input set, and only after a deep analysis by DSpot developers, it was identify the cause. 
Therefore, it would be a great tool usability improvement if:
- dspot.properties is verified for compliance (well conformance, valid values, etc) before DSpot proceeds with amplification
- CLI parameters are also verified for compliance, similarly. 
In particular, DSpot can verify the availability of resources declared in the dspot.properties and CLI parameters (e.g. availability of test cases, pathname, etc)

When an issue related to inputs is detected, DSpot can report to the user, stopping the execution.

**Comment by danglotb** [comment]
Hi, I am working on #659 

Do you have any idea on how to check JVM arguments and system properties?

In fact, in DSpot, one can give JVM args (from the properties file) to be specified, for instance, to execute the tests you need specific JVM args.

But, I do not know how to check these arguments (same for system properties).

Thank you.

**Comment by jesus-gorronogoitia** [comment]
Hi  @danglotb Sorry, I forgot to response to your question. I have no idea about a formal verification. I've been looking for a library on Internet with no success. I think an approach is to proceed internally with the JVM, which will verify passed arguments. Then DSpot can capture and report to the user caller any JVM argument related exception triggered by the JVM
