### ISSUE TITLE
Remove not needed casts in generated tests to have more readable tests

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#688]
Example of generated test (showing a screenshot that shows in light grey what can be removed)

<img width="862" alt="screenshot 2019-02-04 at 09 33 59" src="https://user-images.githubusercontent.com/628267/52197503-18d38e80-2860-11e9-8dc8-5485e05f0e05.png">

**Comment by vmassol** [comment]
BTW a very simple thing to do is to do a static import for `import static org.junit.jupiter.api.Assertions.*;`. This removes all the `Assert.` prefixes and make the code more readable too. :)

**Comment by vmassol** [comment]
Side question: I see this tests calls:

```
        type.getType().getId();
        type.getDataFormat();
        type.getVersion();
```

And then does the same assert again. Couldn't dspot decide to not add the second part since calling the getters has no side effects?

**Comment by danglotb** [comment]
Hi @vmassol 

I'll look at the redundant cast.

> BTW a very simple thing to do is to do a static import for import static org.junit.jupiter.api.Assertions.*;. This removes all the Assert. prefixes and make the code more readable too. :)

This issue comes from Spoon if I remember. A release is announced on the 11th, February. I'm gonna bump the version used by DSpot.

> Couldn't dspot decide to not add the second part since calling the getters has no side effects?

It could. For now, DSpot does not distinguish the "type" of statement between the sequences of assertions. If there is something, (invocation, local variables, etc...) It should generate the second sequence.

Thank you!
