### ISSUE TITLE
Hangs when testing

### ISSUE THREAD

**Issue by Smorka** [STAMP-project/dspot#742]
#### Characteristics
- **Issue Type**: test report
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: dspot 2.0.1
- **Execution Environment**: ubuntu, virtualbox
- **Reporter**: Sverre Morka

#### Description
Trying to execute dspot using the guidelines on GitHub. It seems to be hanging after a while. Tried waiting approximately 2 hours. 
```shell
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ tellulib ---
[INFO] Wrote classpath file '/home/riff/development/tellulib/target/dspot/classpath'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.472 s
[INFO] Finished at: 2019-04-05T12:04:18Z
[INFO] Final Memory: 22M/306M
[INFO] ------------------------------------------------------------------------
[INFO] 2019-04-05 14:04:21 Amplification - Amplification of no.tellu.lib.data.model.ModelTest (12 test(s))
[INFO] 2019-04-05 14:04:21 Amplification - Assertion amplification of no.tellu.lib.data.model.ModelTest (12 test(s))
[INFO] 2019-04-05 14:04:21 EhcacheManager - Cache 'frameworkCache' created in EhcacheManager.
[INFO] 2019-04-05 14:04:23 MavenAutomaticBuilder - Using /home/riff/development/tellulib/././.dspot_pom.xml to run maven.
[INFO] 2019-04-05 14:04:23 MavenAutomaticBuilder - Using /usr/share/maven/ for maven home
[INFO] 2019-04-05 14:04:23 MavenAutomaticBuilder - run maven: /usr/share/maven//bin/mvn org.pitest:pitest-maven:mutationCoverage 
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
```

##### Properties file

```java
project=.
targetModule=.
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=dspot-out/
filter=no.tellu.*
```

##### Command Line / Options

```shell
java -jar ../dspot/dspot/target/dspot-2.0.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --test no.tellu.lib.data.model.ModelTest --timeOut 1000
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @Smorka 

We can see in the log:

```txt
[INFO] 2019-04-05 14:04:23 MavenAutomaticBuilder - run maven: /usr/share/maven//bin/mvn org.pitest:pitest-maven:mutationCoverage 
```

This means that DSpot was running PIT on tellulib.

Running PIT can take hours, even days. What we can do is enable the verbose mode of DSpot, in order to print the evolution of PIT.

Add to your command line `--verbose`.

Computing mutation score takes a lot of time because it runs a lot, I mean **A LOT** of time the tests.

On one hand, you can use another test-criterion than mutation score using `--test-criterion` command line option. For instance, you can use `--test-criterion JacocoCoverageSelector` to use the instruction coverage computed with [JaCoCo](https://www.eclemma.org/jacoco/).

On the other hand, if you want to use the mutation score and so PIT, I advise you to run PIT outside of DSpot, keep the mutation analysis, _i.e._ the output of PIT, and give it to DSpot for next executions.

Why would do that? The fact is that before doing anything else, DSpot needs a baseline to compare amplified test methods and original test methods.

For example, you want to increase the branch coverage, _i.e._ you want amplified test methods that cover new branches that are not covered by the original test suite. 
First, you need to know which branches are already covered, so you compute the branch coverage using JaCoCo for instance. You will also know which branches are not covered. During the process, DSpot computes the branch coverage of the amplified test methods and will keep only amplified test methods that cover branches that were not covered by the original test suite. To do this, DSpot compares the branch coverage computed at the beginning and the branch coverage computed with the amplified test methods.

In the same way, if you want to obtain amplified test methods that increase the mutation score you need to compute the mutation score of the original test suite. Increasing the mutation score means increasing the number of mutants killed, so we need to keep amplified test methods that kill mutants that were not killed by the original test suite.

We saw that computing the mutation score takes a lot of time. This is why one can provide to DSpot the pre-computed baseline in order to avoid computing it several times (if want to do several runs of DSpot).

To compute the mutation score, you can: 

1. have a look at the PIT documentation and descartes documentation and run it yourself (you will need to use the output format XML. 
2. use the generated pom by DSpot to run pit. As printed on your stdout: `[INFO] 2019-04-05 14:04:23 MavenAutomaticBuilder - Using /home/riff/development/tellulib/././.dspot_pom.xml to run maven.
`, the pom generated is named `.dspot_pom.xml` and is at the root of your project. You can run pit with:
`mvn org.pitest:pitest-maven:mutationCoverage -f .dspot_pom.xml`

You must retrieve and keep the output of PIT. It should be in `target/pit-reports/AAAAMMDDHHMM/mutations.xml`
And finally, you can provide the baseline of the mutation score to DSpot with `--path-pit-result <pathToFileXML>`.

Thank you, do not hesitate to ask any questions.

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
