### ISSUE TITLE
Is it possible to specify multiple amplifiers from CLI?

### ISSUE THREAD

**Issue by kejsardamberg** [STAMP-project/dspot#752]
#### Characteristics
- **Issue Type**: Question
- **Severity**: minor
- **Tool/Service/Component**: [DSpot, 2.0.0]
- **Reporter**: [Jörgen Damberg]

#### Description
Maybe I've browsed through the documentation too quickly, but I can't find if it's possible to use multiple amplifiers for DSpot from CLI.

**Comment by danglotb** [comment]
Hello @kejsardamberg 

You can specify multiple amplifiers using the command line as follow:

`--amplifiers Amplifies1:Amplifier2:...:AmplifierN`.

For example, I want to run both Input amplifiers `AllLiteralAmplifiers` and `MethodGeneratorAmplifier`. I'll use: `--amplifiers AllLiteralAmplifiers:MethodGeneratorAmplifier`

Here, I used `:` as a separator because I am on Linux. However, you must use the path separator of your own system, _e.g._ for Windows it is `;`.

Keep me update of your progress! :-)

**Comment by danglotb** [comment]
Closing this issue. Do not hesitate to reopen it or open a new one. Thank you.
