### ISSUE TITLE
Questions about DSpot configuration

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#820]
Good afternoon :

1. The parameters excludedClasses and excludedTestCases are compatible with test and test-cases ?

2. The parameter path-to-second-version can be only use with ChangeDetectorSelector ?

3. When using automaticBuilderName=Maven/Gradle the project must be configured as Maven/Gradle ?

Thank you.

**Comment by danglotb** [comment]
Hello @RicardoTej 

> The parameters excludedClasses and excludedTestCases are compatible with test and test-cases?

What do you mean by "compatible"? In fact, you can use both and for example include a whole package but exclude a sub package of it, _e.g._:
```
--test eu.stamp_project.mypackage.*
excludedClasses=eu.stamp_project.mypackage.not.wanted.subpackage.*
```
This is will take all test classes in the package `eu.stamp_project.mypackage.*` but the test classes in `eu.stamp_project.mypackage.not.wanted.subpackage.*`.

> The parameter path-to-second-version can be only used with ChangeDetectorSelector?

For now, it is. There is no other usage. However, if you imagine another usage, you can implement it, there is no restriction.

>When using automaticBuilderName=Maven/Gradle the project must be configured as Maven/Gradle?

Yes, it must be. If your project is a Gradle project but you specify (or not since maven is used by default) `automaticBuilderName=Maven`, then DSpot will try to use maven during the process, thus you will have an error since there is no `pom.xml`.

If you project is a maven project, use the maven automatic builder (by default), if it is a Gradle project, you must specify `automaticBuilderName=Gradle`, otherwise, it won't work.

**Comment by RicardoTej** [comment]
Thank you, It's all I needed
