### ISSUE TITLE
BUG: something is wrong with the mongodb docker image

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#905]
Hello,

I'm trying to run the test locally but it seems that there is an issue with the mongodb docker image.

I run the following:

```
docker run -d --net=host mongo:latest
```

And I have the following error message:
```
edd74e8926fc7e6dc4e4eeef9bbed216cc9305fbab78fc40834d8827262ab917
docker: Error response from daemon: unable to find "cpuacct" in controller set: unknown.
```

Any ideas? @henry-lp

**Comment by henry-lp** [comment]
hi @danglotb :) , this is a bug of docker , it's inside containerd to be precise . 

Related issue to this - [issue 1](https://github.com/docker/for-linux/issues/552) , [issue 2](https://github.com/docker/for-linux/issues/545)  . 

This problem occurs if your `systemd` (use `systemctl --version` if Ubuntu) version is 240 or higher. My is 237 and it still work for me as I just test it out some minutes ago. What you can do 
* Downgrade your system to below 240 
* Install the latest docker nightly - `curl -fsSL get.docker.com | CHANNEL=nightly sh` - [this comment](https://github.com/docker/for-linux/issues/545#issuecomment-512677631_)
* Download and install mongodb without using docker 

Option 2 is best if it works for you, Otherwise you can go with the third option  :).

**Comment by danglotb** [comment]
Thank you for the pointers. I can fix my pr now.
